######################################################################
# Configuation file for Artifical Modular Intelligence (AMI)
#   These are settings for the AI that can only be user configured

# API Keys for services used
together_apikey:

# Landsmith optional
langsmith_apikey:

# Timezone information; run homeai.utils.py:get_timezones() to see a list of inputs here
timezone: America/Los_Angeles

# Silence threshold when listening to the user
silence_threshold: 4

# AI filesystem directory
ai_filesystem: filespace

# This setting, if enabled, saves all voice interations to a directory
recording_dir: recordings

# Server Host
host: 0.0.0.0

# Server Port
port: 5000

# Hot Word is a literal used by openWakeWord for the model to use for hotword detection
# Literal[ "alexa", "hey_mycroft", "hey_jarvis", "hey_rhasspy" ]
hot_word: hey_rhasspy

# Audio Silence Threshold (int) is the audio levels where voice is detected versus not
audio_silence_threshold: 11000

# Log configuration
logging:
  stdout: True
  directory: logs
  # Literal: DEBUG | INFO | WARNING | ERROR | CRITICAL
  level: WARNING

# QR Codes are saved to this directory
#TODO Delete this
#DEPRICATE THIS
qr_directory: qr_codes

# Modules
## Modules are essentionally 3rd party agents
## The defaults in modules at core run the AI

# 3rd Party Module Headspaces directory
modules_dir: modules

# Enabled Headspaces (core and imported)
enabled_headspaces:
  - time
  - markdown
  - calendar
